
package practica2;
import javax.swing.table.DefaultTableModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import practica2.historialPedidos;

/**
 *
 * @author jaswl
 */
public class Pedidos extends javax.swing.JFrame {

   private int [] listaRep = {0, 0, 0};
   private int contDistancias = 0;
     private LocalDateTime momentoPedido;
    /**
     * Creates new form Pedidos
     */
    public Pedidos() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Pedidos");
        
        
        addProdEnvio.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            int selectedRow = ListaProductos.getSelectedRow();
                if (selectedRow != -1) {
            String producto = (String) ListaProductos.getValueAt(selectedRow, 0);
            String precio = (String) ListaProductos.getValueAt(selectedRow, 1);
            Object[] nuevoProductoEnv = {producto, precio};
            modeloListaProductosEnv.addRow(nuevoProductoEnv);
            System.out.println("Producto agregado al pedido");
                } else {
            System.out.println("No se ha seleccionado ninguna fila");
        }
    }
});

    }
    private DefaultTableModel modeloListaProductosEnv;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaProductos = new javax.swing.JTable();
        nomProd = new javax.swing.JTextField();
        crearActivBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaProductosEnv = new javax.swing.JTable();
        addProdEnvio = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();
        precioLbl = new javax.swing.JLabel();
        boxRepartidor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtKm = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        confPedido = new javax.swing.JButton();
        recorridoBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Precio");

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        ListaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Combo 4 piezas de pollo", "40"},
                {"Porcion papas fritas", "8"},
                {"Hamburguesa de pollo", "15"},
                {"nuggets de pollo 6 u", "18"}
            },
            new String [] {
                "Producto", "Precio"
            }
        ));
        jScrollPane2.setViewportView(ListaProductos);

        nomProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomProdActionPerformed(evt);
            }
        });

        crearActivBtn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        crearActivBtn.setText("Agregar producto a la lista");
        crearActivBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActivBtnActionPerformed(evt);
            }
        });

        ListaProductosEnv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio"
            }
        ));
        jScrollPane3.setViewportView(ListaProductosEnv);
        modeloListaProductosEnv = (DefaultTableModel) ListaProductosEnv.getModel();

        addProdEnvio.setText("Agregar producto al pedido");
        addProdEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProdEnvioActionPerformed(evt);
            }
        });

        totalLabel.setText("Total (Q.)");

        precioLbl.setText("0");

        boxRepartidor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Repartidor 1", "Repartidor 2", "Repartidor 3" }));
        boxRepartidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxRepartidorActionPerformed(evt);
            }
        });

        jLabel5.setText("Distancia del pedido:");

        txtKm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKmActionPerformed(evt);
            }
        });

        jLabel6.setText("KM");

        confPedido.setText("Confirmar Pedido");
        confPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confPedidoActionPerformed(evt);
            }
        });

        recorridoBtn.setText("Ir al recorrido");
        recorridoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recorridoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nomProd, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(257, 257, 257)
                                .addComponent(totalLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precioLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addProdEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boxRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtKm, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(crearActivBtn)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recorridoBtn)
                    .addComponent(confPedido))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nomProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalLabel)
                            .addComponent(precioLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(crearActivBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(addProdEnvio)
                        .addGap(18, 18, 18)
                        .addComponent(boxRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(confPedido)
                .addGap(18, 18, 18)
                .addComponent(recorridoBtn)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomProdActionPerformed

    private void crearActivBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActivBtnActionPerformed
        // TODO add your handling code here:
        String nomProducto = nomProd.getText();
        String vPrecio = txtPrecio.getText();

        Object[] nuevoProducto = {nomProducto, vPrecio};
        DefaultTableModel modeloListaActividades = (DefaultTableModel) ListaProductos.getModel();
        modeloListaActividades.addRow(nuevoProducto);
        nomProd.setText("");
        txtPrecio.setText("");
        System.out.println("Producto Agregado");
    }//GEN-LAST:event_crearActivBtnActionPerformed

    private void addProdEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProdEnvioActionPerformed
        // TODO add your handling code here:
         double total = 0.0;
        for (int i = 0; i < modeloListaProductosEnv.getRowCount(); i++) {
            double precio = Double.parseDouble(modeloListaProductosEnv.getValueAt(i, 1).toString());
            total += precio;
        }
        
        // Mostrar el resultado en el JLabel precioLbl
        precioLbl.setText(String.valueOf(total));

    }//GEN-LAST:event_addProdEnvioActionPerformed

    private void confPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confPedidoActionPerformed
        // TODO add your handling code here:
        int distKm = Integer.parseInt(txtKm.getText());
        if(boxRepartidor.getSelectedItem().toString() == "Repartidor 1"){
            listaRep[0] = distKm;
          
        } else if (boxRepartidor.getSelectedItem().toString() == "Repartidor 2"){
            listaRep[1] = distKm;
           
        } else if (boxRepartidor.getSelectedItem().toString() == "Repartidor 3"){
            listaRep[2] = distKm;
            
        }
        

        txtKm.setText("");
        precioLbl.setText("");
        System.out.println("Producto Agregado");
        int recorrido = Integer.parseInt(txtKm.getText());
        String repartidor = boxRepartidor.getSelectedItem().toString();
        int monto =  Integer.parseInt(precioLbl.getText());
         momentoPedido = LocalDateTime.now();


        Pedido cantiPedidos = new Pedido (repartidor, recorrido, monto, momentoPedido);
        int contadorPedido = historialPedidos.contadorPedido;

        historialPedidos.cantPedidos[contadorPedido] = cantiPedidos;

        historialPedidos.contadorPedido++;
        
        System.out.println("Agregado");
        
    }//GEN-LAST:event_confPedidoActionPerformed

    private void recorridoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recorridoBtnActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        visTrayectorias vt = new visTrayectorias(listaRep); 
        vt.setVisible(true);
        contDistancias = 0;
        listaRep[0] = 0;
        listaRep[1] = 0;
        listaRep[2] = 0;
    }//GEN-LAST:event_recorridoBtnActionPerformed

    private void txtKmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKmActionPerformed

    private void boxRepartidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxRepartidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxRepartidorActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed


    private double calcularTotal() {
    double total = 0.0;
    for (int i = 0; i < modeloListaProductosEnv.getRowCount(); i++) {
        double precio = Double.parseDouble(modeloListaProductosEnv.getValueAt(i, 1).toString());
        total += precio;
    }
    return total;
}
    

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ListaProductos;
    private javax.swing.JTable ListaProductosEnv;
    private javax.swing.JButton addProdEnvio;
    private javax.swing.JComboBox<String> boxRepartidor;
    private javax.swing.JButton confPedido;
    private javax.swing.JButton crearActivBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nomProd;
    private javax.swing.JLabel precioLbl;
    private javax.swing.JButton recorridoBtn;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTextField txtKm;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
