/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author jaswl
 */
public class visTrayectorias extends javax.swing.JFrame {
    private int [] listaRep = new int [3];
    private JTextField confPedido;
    
    /**
     * Creates new form visTrayectorias
     */
    public visTrayectorias(int[] listaRep) {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Trayectoria Repartidores");
        this.listaRep[0] = listaRep[0];
        this.listaRep[1] = listaRep[1];
        this.listaRep[2] = listaRep[2];
        
    }
    
    public JLabel getrepartidor1(){
        return rep1;
    }    
     
    public JLabel getrepartidor2(){
        return rep2;
    }
    
    public JLabel getrepartidor3 (){
        return rep3;
    }
    
    public JLabel getMeta(){
        return meta;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rep2 = new javax.swing.JLabel();
        meta = new javax.swing.JLabel();
        rep3 = new javax.swing.JLabel();
        rep1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EnviarR1Btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        EnviarR2Btn = new javax.swing.JButton();
        EnviarR3Btn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        EnvTodosRBtn = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        historialBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Visualización de Trayectorias");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rep2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/repartidor1.png"))); // NOI18N

        meta.setBackground(new java.awt.Color(255, 0, 51));
        meta.setOpaque(true);

        rep3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/repartidor1.png"))); // NOI18N

        rep1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/repartidor1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rep2)
                    .addComponent(rep3)
                    .addComponent(rep1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 670, Short.MAX_VALUE)
                .addComponent(meta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(meta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(rep1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(rep2)
                .addGap(89, 89, 89)
                .addComponent(rep3)
                .addGap(80, 80, 80))
        );

        jLabel2.setText("Repartidor 1");

        EnviarR1Btn.setText("Enviar");
        EnviarR1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarR1BtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Repartidor 2");

        EnviarR2Btn.setText("Enviar");
        EnviarR2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarR2BtnActionPerformed(evt);
            }
        });

        EnviarR3Btn.setText("Enviar");
        EnviarR3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarR3BtnActionPerformed(evt);
            }
        });

        jLabel12.setText("Repartidor 3");

        EnvTodosRBtn.setText("Enviar a Todos");
        EnvTodosRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnvTodosRBtnActionPerformed(evt);
            }
        });

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        historialBtn.setText("Historial");
        historialBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EnviarR1Btn)
                            .addComponent(jLabel6)
                            .addComponent(EnviarR2Btn)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12)
                            .addComponent(EnviarR3Btn))
                        .addGap(51, 51, 51)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(EnvTodosRBtn)
                        .addGap(73, 73, 73)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(historialBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(EnvTodosRBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regresar)
                    .addComponent(historialBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addComponent(EnviarR1Btn)
                .addGap(186, 186, 186)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(EnviarR2Btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EnviarR3Btn)
                .addGap(164, 164, 164))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnviarR1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarR1BtnActionPerformed
        
        trayectoria hilo1 = new trayectoria(rep1, this, 10, listaRep[0]);
        hilo1.start();
         
        

    }//GEN-LAST:event_EnviarR1BtnActionPerformed

    private void EnviarR2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarR2BtnActionPerformed
        
        trayectoria hilo2 = new trayectoria(rep2, this, 10, listaRep[1]);
        hilo2.start();
    }//GEN-LAST:event_EnviarR2BtnActionPerformed

    private void EnviarR3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarR3BtnActionPerformed
        
        trayectoria hilo3 = new trayectoria(rep3, this, 10, listaRep[2]);
        hilo3.start();
    }//GEN-LAST:event_EnviarR3BtnActionPerformed

    private void EnvTodosRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnvTodosRBtnActionPerformed
        // TODO add your handling code here:
        rep1.setLocation(0,rep1.getLocation().y);
        rep2.setLocation(0,rep2.getLocation().y);
        rep3.setLocation(0,rep3.getLocation().y);
        
        trayectoria hilo1 = new trayectoria(rep1, this, 10, listaRep[0]);
        trayectoria hilo2 = new trayectoria(rep2, this, 10, listaRep[1]);
        trayectoria hilo3 = new trayectoria(rep3, this, 10, listaRep[2]);
    
         hilo1.start();
         hilo2.start();
         hilo3.start();
        
    }//GEN-LAST:event_EnvTodosRBtnActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Pedidos pd = new Pedidos(); 
        pd.setVisible(true);
    }//GEN-LAST:event_regresarActionPerformed

    private void historialBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        historialPedidos hs = new historialPedidos(); 
        hs.setVisible(true);
    }//GEN-LAST:event_historialBtnActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visTrayectorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visTrayectorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visTrayectorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visTrayectorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnvTodosRBtn;
    private javax.swing.JButton EnviarR1Btn;
    private javax.swing.JButton EnviarR2Btn;
    private javax.swing.JButton EnviarR3Btn;
    private javax.swing.JButton historialBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel meta;
    private javax.swing.JButton regresar;
    private javax.swing.JLabel rep1;
    private javax.swing.JLabel rep2;
    private javax.swing.JLabel rep3;
    // End of variables declaration//GEN-END:variables
}
